# Authentication
auth_service: None  # one of: None, ptc, google
username: 'MyUsername' 
password: 'MySuperStrongPassword'

# Location that google maps understands
location: 'Boulder, CO' 
# Steps to take, typically 2-5
step_limit: 5 

# What to plot on the map
display_pokestop: False
display_gym: False
 # Pokenon to ignore
ignore: None # [ 13, 16 ]
# The only pokemon that should be displayed
only: None # [ 150, 151 ] 

# UI
locale: 'en' 
# Autofresh, None or integer value in seconds
auto_refresh: None 
# Debug-level logging
debug: False 

# Use China transformer
china: False  

# Web server host and port, defaults to localhost:3000
host: '127.0.0.1' 
port: 5000 
